services:
  - type: web
    name: repository-review
    env: node
    plan: free
    buildCommand: |
      npm install && npm run build --prefix client
    startCommand: npm start --prefix server
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: /api/$1